import "~/styles/globals.css";

import {Inter} from "next/font/google";

import {TRPCReactProvider} from "~/trpc/react";
import {ThemeProvider} from "~/providers/theme";
import {TooltipProvider} from "~/components/ui/tooltip";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{rel: "icon", url: "/favicon.ico"}],
};

export default function RootLayout({children}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <ThemeProvider attribute="class" defaultTheme="dark">
            <TooltipProvider>
                <body className={`font-sans ${inter.variable}`}>
                <TRPCReactProvider>{children}</TRPCReactProvider>
                </body>
            </TooltipProvider>
        </ThemeProvider>
        </html>
    )

}
